// Code generated by MockGen. DO NOT EDIT.
// Source: admin_service.go
//
// Generated by this command:
//
//	mockgen -source=admin_service.go -destination=mock_admin_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "github.com/Magetan-Boyz/Backend/internal/domain/dto"
	entities "github.com/Magetan-Boyz/Backend/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockAdminService is a mock of AdminService interface.
type MockAdminService struct {
	ctrl     *gomock.Controller
	recorder *MockAdminServiceMockRecorder
}

// MockAdminServiceMockRecorder is the mock recorder for MockAdminService.
type MockAdminServiceMockRecorder struct {
	mock *MockAdminService
}

// NewMockAdminService creates a new mock instance.
func NewMockAdminService(ctrl *gomock.Controller) *MockAdminService {
	mock := &MockAdminService{ctrl: ctrl}
	mock.recorder = &MockAdminServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminService) EXPECT() *MockAdminServiceMockRecorder {
	return m.recorder
}

// AssignHomeroomTeacher mocks base method.
func (m *MockAdminService) AssignHomeroomTeacher(classID, teacherID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignHomeroomTeacher", classID, teacherID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignHomeroomTeacher indicates an expected call of AssignHomeroomTeacher.
func (mr *MockAdminServiceMockRecorder) AssignHomeroomTeacher(classID, teacherID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignHomeroomTeacher", reflect.TypeOf((*MockAdminService)(nil).AssignHomeroomTeacher), classID, teacherID)
}

// AssignParentToStudent mocks base method.
func (m *MockAdminService) AssignParentToStudent(parentID, studentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignParentToStudent", parentID, studentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignParentToStudent indicates an expected call of AssignParentToStudent.
func (mr *MockAdminServiceMockRecorder) AssignParentToStudent(parentID, studentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignParentToStudent", reflect.TypeOf((*MockAdminService)(nil).AssignParentToStudent), parentID, studentID)
}

// AssignSubjectToClass mocks base method.
func (m *MockAdminService) AssignSubjectToClass(subjectID, teacherID, classID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignSubjectToClass", subjectID, teacherID, classID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignSubjectToClass indicates an expected call of AssignSubjectToClass.
func (mr *MockAdminServiceMockRecorder) AssignSubjectToClass(subjectID, teacherID, classID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignSubjectToClass", reflect.TypeOf((*MockAdminService)(nil).AssignSubjectToClass), subjectID, teacherID, classID)
}

// AssignTeacherToSubject mocks base method.
func (m *MockAdminService) AssignTeacherToSubject(teacherID, SubjectID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignTeacherToSubject", teacherID, SubjectID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignTeacherToSubject indicates an expected call of AssignTeacherToSubject.
func (mr *MockAdminServiceMockRecorder) AssignTeacherToSubject(teacherID, SubjectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignTeacherToSubject", reflect.TypeOf((*MockAdminService)(nil).AssignTeacherToSubject), teacherID, SubjectID)
}

// ClassExists mocks base method.
func (m *MockAdminService) ClassExists(classID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClassExists", classID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClassExists indicates an expected call of ClassExists.
func (mr *MockAdminServiceMockRecorder) ClassExists(classID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClassExists", reflect.TypeOf((*MockAdminService)(nil).ClassExists), classID)
}

// CreateAnnouncement mocks base method.
func (m *MockAdminService) CreateAnnouncement(announcement *entities.Announcement) (*entities.Announcement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAnnouncement", announcement)
	ret0, _ := ret[0].(*entities.Announcement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAnnouncement indicates an expected call of CreateAnnouncement.
func (mr *MockAdminServiceMockRecorder) CreateAnnouncement(announcement any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAnnouncement", reflect.TypeOf((*MockAdminService)(nil).CreateAnnouncement), announcement)
}

// CreateClass mocks base method.
func (m *MockAdminService) CreateClass(class *entities.Class) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateClass", class)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateClass indicates an expected call of CreateClass.
func (mr *MockAdminServiceMockRecorder) CreateClass(class any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClass", reflect.TypeOf((*MockAdminService)(nil).CreateClass), class)
}

// CreateParent mocks base method.
func (m *MockAdminService) CreateParent(parent *entities.Parent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateParent", parent)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateParent indicates an expected call of CreateParent.
func (mr *MockAdminServiceMockRecorder) CreateParent(parent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateParent", reflect.TypeOf((*MockAdminService)(nil).CreateParent), parent)
}

// CreateSchedule mocks base method.
func (m *MockAdminService) CreateSchedule(schedule *entities.Schedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSchedule", schedule)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSchedule indicates an expected call of CreateSchedule.
func (mr *MockAdminServiceMockRecorder) CreateSchedule(schedule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSchedule", reflect.TypeOf((*MockAdminService)(nil).CreateSchedule), schedule)
}

// CreateStudent mocks base method.
func (m *MockAdminService) CreateStudent(student *entities.Student) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStudent", student)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateStudent indicates an expected call of CreateStudent.
func (mr *MockAdminServiceMockRecorder) CreateStudent(student any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStudent", reflect.TypeOf((*MockAdminService)(nil).CreateStudent), student)
}

// CreateSubject mocks base method.
func (m *MockAdminService) CreateSubject(subject *entities.Subject) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubject", subject)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSubject indicates an expected call of CreateSubject.
func (mr *MockAdminServiceMockRecorder) CreateSubject(subject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubject", reflect.TypeOf((*MockAdminService)(nil).CreateSubject), subject)
}

// CreateTeacher mocks base method.
func (m *MockAdminService) CreateTeacher(teacher *entities.Teacher) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTeacher", teacher)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTeacher indicates an expected call of CreateTeacher.
func (mr *MockAdminServiceMockRecorder) CreateTeacher(teacher any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTeacher", reflect.TypeOf((*MockAdminService)(nil).CreateTeacher), teacher)
}

// DeleteAnnouncement mocks base method.
func (m *MockAdminService) DeleteAnnouncement(announcementID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAnnouncement", announcementID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAnnouncement indicates an expected call of DeleteAnnouncement.
func (mr *MockAdminServiceMockRecorder) DeleteAnnouncement(announcementID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAnnouncement", reflect.TypeOf((*MockAdminService)(nil).DeleteAnnouncement), announcementID)
}

// FindClassByID mocks base method.
func (m *MockAdminService) FindClassByID(id string) (*entities.Class, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindClassByID", id)
	ret0, _ := ret[0].(*entities.Class)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindClassByID indicates an expected call of FindClassByID.
func (mr *MockAdminServiceMockRecorder) FindClassByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindClassByID", reflect.TypeOf((*MockAdminService)(nil).FindClassByID), id)
}

// FindSubjectByID mocks base method.
func (m *MockAdminService) FindSubjectByID(id string) (*entities.Subject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSubjectByID", id)
	ret0, _ := ret[0].(*entities.Subject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSubjectByID indicates an expected call of FindSubjectByID.
func (mr *MockAdminServiceMockRecorder) FindSubjectByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSubjectByID", reflect.TypeOf((*MockAdminService)(nil).FindSubjectByID), id)
}

// FindTeacherByID mocks base method.
func (m *MockAdminService) FindTeacherByID(id string) (*entities.Teacher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTeacherByID", id)
	ret0, _ := ret[0].(*entities.Teacher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTeacherByID indicates an expected call of FindTeacherByID.
func (mr *MockAdminServiceMockRecorder) FindTeacherByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTeacherByID", reflect.TypeOf((*MockAdminService)(nil).FindTeacherByID), id)
}

// GetAllClass mocks base method.
func (m *MockAdminService) GetAllClass() ([]entities.Class, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllClass")
	ret0, _ := ret[0].([]entities.Class)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllClass indicates an expected call of GetAllClass.
func (mr *MockAdminServiceMockRecorder) GetAllClass() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllClass", reflect.TypeOf((*MockAdminService)(nil).GetAllClass))
}

// GetAllStudents mocks base method.
func (m *MockAdminService) GetAllStudents() ([]entities.Student, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllStudents")
	ret0, _ := ret[0].([]entities.Student)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllStudents indicates an expected call of GetAllStudents.
func (mr *MockAdminServiceMockRecorder) GetAllStudents() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllStudents", reflect.TypeOf((*MockAdminService)(nil).GetAllStudents))
}

// GetAllStudentsBelongToClass mocks base method.
func (m *MockAdminService) GetAllStudentsBelongToClass(studentID string) ([]entities.Student, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllStudentsBelongToClass", studentID)
	ret0, _ := ret[0].([]entities.Student)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllStudentsBelongToClass indicates an expected call of GetAllStudentsBelongToClass.
func (mr *MockAdminServiceMockRecorder) GetAllStudentsBelongToClass(studentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllStudentsBelongToClass", reflect.TypeOf((*MockAdminService)(nil).GetAllStudentsBelongToClass), studentID)
}

// GetAllSubject mocks base method.
func (m *MockAdminService) GetAllSubject() ([]entities.Subject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSubject")
	ret0, _ := ret[0].([]entities.Subject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSubject indicates an expected call of GetAllSubject.
func (mr *MockAdminServiceMockRecorder) GetAllSubject() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSubject", reflect.TypeOf((*MockAdminService)(nil).GetAllSubject))
}

// GetAllTeacher mocks base method.
func (m *MockAdminService) GetAllTeacher() ([]entities.Teacher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTeacher")
	ret0, _ := ret[0].([]entities.Teacher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTeacher indicates an expected call of GetAllTeacher.
func (mr *MockAdminServiceMockRecorder) GetAllTeacher() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTeacher", reflect.TypeOf((*MockAdminService)(nil).GetAllTeacher))
}

// GetAnnouncementByID mocks base method.
func (m *MockAdminService) GetAnnouncementByID(announcementID string) (*entities.Announcement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnnouncementByID", announcementID)
	ret0, _ := ret[0].(*entities.Announcement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAnnouncementByID indicates an expected call of GetAnnouncementByID.
func (mr *MockAdminServiceMockRecorder) GetAnnouncementByID(announcementID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnnouncementByID", reflect.TypeOf((*MockAdminService)(nil).GetAnnouncementByID), announcementID)
}

// GetAnnouncements mocks base method.
func (m *MockAdminService) GetAnnouncements() ([]entities.Announcement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnnouncements")
	ret0, _ := ret[0].([]entities.Announcement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAnnouncements indicates an expected call of GetAnnouncements.
func (mr *MockAdminServiceMockRecorder) GetAnnouncements() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnnouncements", reflect.TypeOf((*MockAdminService)(nil).GetAnnouncements))
}

// GetClassSchedule mocks base method.
func (m *MockAdminService) GetClassSchedule(classID string) ([]entities.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClassSchedule", classID)
	ret0, _ := ret[0].([]entities.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClassSchedule indicates an expected call of GetClassSchedule.
func (mr *MockAdminServiceMockRecorder) GetClassSchedule(classID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClassSchedule", reflect.TypeOf((*MockAdminService)(nil).GetClassSchedule), classID)
}

// GetPreloadSchedule mocks base method.
func (m *MockAdminService) GetPreloadSchedule() (*entities.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPreloadSchedule")
	ret0, _ := ret[0].(*entities.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPreloadSchedule indicates an expected call of GetPreloadSchedule.
func (mr *MockAdminServiceMockRecorder) GetPreloadSchedule() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPreloadSchedule", reflect.TypeOf((*MockAdminService)(nil).GetPreloadSchedule))
}

// GetScheduleByID mocks base method.
func (m *MockAdminService) GetScheduleByID(id string) (*entities.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScheduleByID", id)
	ret0, _ := ret[0].(*entities.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScheduleByID indicates an expected call of GetScheduleByID.
func (mr *MockAdminServiceMockRecorder) GetScheduleByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScheduleByID", reflect.TypeOf((*MockAdminService)(nil).GetScheduleByID), id)
}

// GetTeacherSubjects mocks base method.
func (m *MockAdminService) GetTeacherSubjects(teacherID string) ([]dto.TeacherSubjectsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeacherSubjects", teacherID)
	ret0, _ := ret[0].([]dto.TeacherSubjectsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeacherSubjects indicates an expected call of GetTeacherSubjects.
func (mr *MockAdminServiceMockRecorder) GetTeacherSubjects(teacherID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeacherSubjects", reflect.TypeOf((*MockAdminService)(nil).GetTeacherSubjects), teacherID)
}

// GetTeachersBySubjectID mocks base method.
func (m *MockAdminService) GetTeachersBySubjectID(subjectID string) ([]dto.TeacherSubjectResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeachersBySubjectID", subjectID)
	ret0, _ := ret[0].([]dto.TeacherSubjectResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeachersBySubjectID indicates an expected call of GetTeachersBySubjectID.
func (mr *MockAdminServiceMockRecorder) GetTeachersBySubjectID(subjectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeachersBySubjectID", reflect.TypeOf((*MockAdminService)(nil).GetTeachersBySubjectID), subjectID)
}

// InsertStudentToClass mocks base method.
func (m *MockAdminService) InsertStudentToClass(studentID, classID string) (*entities.Student, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertStudentToClass", studentID, classID)
	ret0, _ := ret[0].(*entities.Student)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertStudentToClass indicates an expected call of InsertStudentToClass.
func (mr *MockAdminServiceMockRecorder) InsertStudentToClass(studentID, classID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertStudentToClass", reflect.TypeOf((*MockAdminService)(nil).InsertStudentToClass), studentID, classID)
}

// IsScheduleExists mocks base method.
func (m *MockAdminService) IsScheduleExists(classID, subjectID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsScheduleExists", classID, subjectID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsScheduleExists indicates an expected call of IsScheduleExists.
func (mr *MockAdminServiceMockRecorder) IsScheduleExists(classID, subjectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsScheduleExists", reflect.TypeOf((*MockAdminService)(nil).IsScheduleExists), classID, subjectID)
}

// IsTeacherAssignedToSubject mocks base method.
func (m *MockAdminService) IsTeacherAssignedToSubject(teacherID, subjectID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTeacherAssignedToSubject", teacherID, subjectID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsTeacherAssignedToSubject indicates an expected call of IsTeacherAssignedToSubject.
func (mr *MockAdminServiceMockRecorder) IsTeacherAssignedToSubject(teacherID, subjectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTeacherAssignedToSubject", reflect.TypeOf((*MockAdminService)(nil).IsTeacherAssignedToSubject), teacherID, subjectID)
}

// RemoveStudentFromClass mocks base method.
func (m *MockAdminService) RemoveStudentFromClass(studentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveStudentFromClass", studentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveStudentFromClass indicates an expected call of RemoveStudentFromClass.
func (mr *MockAdminServiceMockRecorder) RemoveStudentFromClass(studentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveStudentFromClass", reflect.TypeOf((*MockAdminService)(nil).RemoveStudentFromClass), studentID)
}

// RemoveStudentsFromClass mocks base method.
func (m *MockAdminService) RemoveStudentsFromClass(classID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveStudentsFromClass", classID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveStudentsFromClass indicates an expected call of RemoveStudentsFromClass.
func (mr *MockAdminServiceMockRecorder) RemoveStudentsFromClass(classID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveStudentsFromClass", reflect.TypeOf((*MockAdminService)(nil).RemoveStudentsFromClass), classID)
}

// UpdateAnnouncement mocks base method.
func (m *MockAdminService) UpdateAnnouncement(announcement *entities.Announcement) (*entities.Announcement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAnnouncement", announcement)
	ret0, _ := ret[0].(*entities.Announcement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAnnouncement indicates an expected call of UpdateAnnouncement.
func (mr *MockAdminServiceMockRecorder) UpdateAnnouncement(announcement any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAnnouncement", reflect.TypeOf((*MockAdminService)(nil).UpdateAnnouncement), announcement)
}

// UpdateTeacherHomeroomStatus mocks base method.
func (m *MockAdminService) UpdateTeacherHomeroomStatus(teacherID string, isHomeroom bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTeacherHomeroomStatus", teacherID, isHomeroom)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTeacherHomeroomStatus indicates an expected call of UpdateTeacherHomeroomStatus.
func (mr *MockAdminServiceMockRecorder) UpdateTeacherHomeroomStatus(teacherID, isHomeroom any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTeacherHomeroomStatus", reflect.TypeOf((*MockAdminService)(nil).UpdateTeacherHomeroomStatus), teacherID, isHomeroom)
}

// UpdateTeacherIsCouncelorStatus mocks base method.
func (m *MockAdminService) UpdateTeacherIsCouncelorStatus(teacherID string, isCouncelor bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTeacherIsCouncelorStatus", teacherID, isCouncelor)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTeacherIsCouncelorStatus indicates an expected call of UpdateTeacherIsCouncelorStatus.
func (mr *MockAdminServiceMockRecorder) UpdateTeacherIsCouncelorStatus(teacherID, isCouncelor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTeacherIsCouncelorStatus", reflect.TypeOf((*MockAdminService)(nil).UpdateTeacherIsCouncelorStatus), teacherID, isCouncelor)
}
